name: Pos Release Workflow

# Event for the workflow
on:
  push:
    branches: [master]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore(auto-merge): sync develop after release'
