name: 'PR Checker'
on:
  pull_request:
    branches:
      - develop
    types: [opened, edited]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Completed Tasks
        uses: kentaro-m/task-completed-checker-action@v0.1.0
        with:
          repo-token: '${{ secrets.PERSONAL_GIT_TOKEN }}'
